In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import csv
import os
import re
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from pykrx import stock
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, silhouette_score
import FinanceDataReader as fdr
import yfinance as yf
import seaborn as sns
import warnings
warnings.filterwarnings(action = "ignore")

pd.set_option('display.max_rows', None)

In [2]:
stock_list = []
BaseUrl = 'http://finance.naver.com/sise/entryJongmok.nhn?&page='

for i in range(1, 21):
    url = BaseUrl + str(i)
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'lxml')
    items = soup.find_all('td', {'class': 'ctg'})

    for item in items:
        # print(item)
        txt = item.a.get('href') 
        k = re.search('[\d]+', txt) ##정규표현식 사용. [\d] 숫자표현, + : 반복
        
        if k:
            code = k.group()
            name = item.text
            data = code, name
            stock_list.append(data)
            

# 코스피 상위 200 종목 이름 가져오기
stock_name = []            
for i in range(len(stock_list)):
    stock_name.append(stock_list[i][1])
    
stock_code = []
for i in range(len(stock_list)):
    stock_code.append(stock_list[i][0])

In [3]:
a = pd.DataFrame(stock_code)
b = pd.DataFrame(stock_name)
df_krx = pd.concat([a,b], axis=1)
df_krx.columns = ["Symbol","Name"]
df_krx.head()

   Symbol      Name
0  005930      삼성전자
1  373220  LG에너지솔루션
2  000660    SK하이닉스
3  207940  삼성바이오로직스
4  006400     삼성SDI

In [7]:
import OpenDartReader
api_key = '32203f64a95fa0bc4f72dc1ff7839ec1b4bbe9bd'
dart = OpenDartReader(api_key)

In [95]:
df_list = []
for i in range(0,200):
    try:
        fin = dart.finstate(df_krx["Name"][i], 2016)
        val = fin[fin["account_nm"] == "매출액"]["thstrm_amount"].iloc[-1]
        df = pd.DataFrame({df_krx["Name"][i] : [val]}, index=[2016])
        df_list.append(df)
    except:
        pass
df = pd.concat(df_list, axis=1)
print(df)

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

                     삼성전자              SK하이닉스              삼성SDI  \
2016  133,947,204,000,000  16,733,111,000,000  4,422,860,766,602

                    LG화학              NAVER            POSCO홀딩스  \
2016  17,264,845,000,000  2,496,498,317,219  24,324,933,259,995

                   현대모비스             포스코케미칼                LG전자  \
2016  19,860,589,000,000  1,076,455,299,180  28,743,246,000,000

                SK이노베이션  ...               KG스틸          녹십자홀딩스  \
2016  1,199,714,934,000  ...  1,542,880,719,243  98,335,181,791

                     대상             현대그린푸드               한섬            현대홈쇼핑  \
2016  1,852,714,894,145  1,554,226,963,000  710,321,856,289  961,339,683,153

                   한세실업             세방전지        화승엔터프라이즈               보령
2016  1,421,975,960,308  958,982,088,874  35,967,805,991  409,140,006,900

[1 rows x 122 columns]

In [67]:
df_list = []
for i in range(0,200):
    try:
        fin = dart.finstate(df_krx["Name"][i], 2017)
        val = fin[fin["account_nm"] == "매출액"]["thstrm_amount"].iloc[-1]
        df = pd.DataFrame({df_krx["Name"][i] : [val]}, index=[2017])
        df_list.append(df)
    except:
        pass
df1 = pd.concat(df_list, axis=1)
print(df1)

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

                     삼성전자              SK하이닉스         삼성바이오로직스  \
2017  161,915,007,000,000  29,718,939,000,000  464,629,334,143

                  삼성SDI                LG화학              NAVER  \
2017  5,421,388,951,623  20,880,236,000,000  2,930,661,324,862

                POSCO홀딩스               현대모비스             포스코케미칼  \
2017  28,553,814,576,380  19,417,685,000,000  1,163,917,965,558

                    LG전자  ...           녹십자홀딩스                 대상  \
2017  31,966,513,000,000  ...  115,366,470,969  2,190,129,354,256

                  지누스             현대그린푸드               한섬              현대홈쇼핑  \
2017  299,097,492,786  1,477,451,922,000  765,914,995,234  1,021,841,020,147

                   한세실업               세방전지         화승엔터프라이즈               보령
2017  1,354,626,971,623  1,108,228,132,369  768,224,189,587  422,721,051,680

[1 rows x 127 columns]

In [68]:
df_list = []
for i in range(0,200):
    try:
        fin = dart.finstate(df_krx["Name"][i], 2018)
        val = fin[fin["account_nm"] == "매출액"]["thstrm_amount"].iloc[-1]
        df = pd.DataFrame({df_krx["Name"][i] : [val]}, index=[2018])
        df_list.append(df)
    except:
        pass
df2 = pd.concat(df_list, axis=1)
print(df2)

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

                     삼성전자              SK하이닉스         삼성바이오로직스  \
2018  170,381,870,000,000  40,324,651,000,000  535,805,801,067

                  삼성SDI                LG화학              NAVER  \
2018  8,186,909,424,218  23,315,318,000,000  3,459,014,042,545

                POSCO홀딩스               현대모비스             포스코케미칼  \
2018  30,659,425,433,515  20,517,169,000,000  1,340,983,671,872

                    LG전자  ...                 대상          HDC현대산업개발  \
2018  29,982,010,000,000  ...  2,235,924,262,966  2,793,597,716,191

                  지누스             현대그린푸드               한섬            현대홈쇼핑  \
2018  188,105,041,208  1,514,615,128,000  766,644,344,598  973,453,833,250

                   한세실업               세방전지         화승엔터프라이즈               보령
2018  1,316,638,246,722  1,165,728,777,090  879,226,467,059  460,401,670,473

[1 rows x 131 columns]

In [69]:
df_list = []
for i in range(0,200):
    try:
        fin = dart.finstate(df_krx["Name"][i], 2019)
        val = fin[fin["account_nm"] == "매출액"]["thstrm_amount"].iloc[-1]
        df = pd.DataFrame({df_krx["Name"][i] : [val]}, index=[2019])
        df_list.append(df)
    except:
        pass
df3 = pd.concat(df_list, axis=1)
print(df3)

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

                     삼성전자              SK하이닉스         삼성바이오로직스  \
2019  154,772,859,000,000  25,320,755,000,000  701,591,859,755

                  삼성SDI                LG화학              NAVER  \
2019  8,250,811,204,936  22,312,561,000,000  3,900,013,295,633

                POSCO홀딩스               현대모비스             포스코케미칼  \
2019  30,373,510,738,515  22,624,741,000,000  1,434,507,298,627

                    LG전자  ...                 대상          HDC현대산업개발  \
2019  28,654,467,000,000  ...  2,457,055,173,045  4,211,144,006,960

                  지누스             현대그린푸드               한섬              현대홈쇼핑  \
2019  246,121,950,068  1,542,730,568,000  994,560,575,546  1,030,416,792,521

                   한세실업               세방전지           화승엔터프라이즈               보령
2019  1,533,976,204,952  1,129,805,364,875  1,201,591,250,778  524,268,670,098

[1 rows x 134 columns]

In [70]:
df_list = []
for i in range(0,200):
    try:
        fin = dart.finstate(df_krx["Name"][i], 2020)
        val = fin[fin["account_nm"] == "매출액"]["thstrm_amount"].iloc[-1]
        df = pd.DataFrame({df_krx["Name"][i] : [val]}, index=[2020])
        df_list.append(df)
    except:
        pass
df4 = pd.concat(df_list, axis=1)
print(df4)

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

                     삼성전자         LG에너지솔루션              SK하이닉스  \
2020  166,311,191,000,000  632,954,000,000  30,524,987,000,000

               삼성바이오로직스              삼성SDI                LG화학  \
2020  1,164,776,873,641  9,101,397,946,638  20,830,009,000,000

                  NAVER            POSCO홀딩스               현대모비스  \
2020  4,126,629,312,584  26,509,920,446,184  22,954,483,000,000

                 포스코케미칼  ...                 대상          HDC현대산업개발  \
2020  1,524,145,792,626  ...  2,604,922,341,877  3,659,511,873,386

                  지누스             현대그린푸드                 한섬  \
2020  203,704,517,635  1,512,503,414,000  1,194,779,636,319

                  현대홈쇼핑               한세실업               세방전지  \
2020  1,084,990,445,012  1,657,328,003,744  1,077,016,196,453

               화승엔터프라이즈               보령
2020  1,115,756,451,023  541,445,421,587

[1 rows x 137 columns]

In [71]:
df_list = []
for i in range(0,200):
    try:
        fin = dart.finstate(df_krx["Name"][i], 2021)
        val = fin[fin["account_nm"] == "매출액"]["thstrm_amount"].iloc[-1]
        df = pd.DataFrame({df_krx["Name"][i] : [val]}, index=[2021])
        df_list.append(df)
    except:
        pass
df5 = pd.concat(df_list, axis=1)
print(df5)

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

{'status': '013', 'message': '조회된 데이타가 없습니다.'}

                     삼성전자           LG에너지솔루션              SK하이닉스  \
2021  199,744,705,000,000  8,387,463,000,000  41,557,337,000,000

               삼성바이오로직스               삼성SDI                LG화학  \
2021  1,568,006,928,039  11,581,771,056,654  20,471,044,000,000

                  NAVER            POSCO홀딩스               현대모비스  \
2021  5,018,667,294,374  39,920,200,836,624  27,328,555,000,000

                 포스코케미칼  ...          HDC현대산업개발              지누스  \
2021  1,939,523,998,420  ...  3,430,672,580,519  333,176,642,785

                 현대그린푸드                 한섬              현대홈쇼핑  \
2021  1,671,200,575,000  1,384,773,095,673  1,080,403,665,439

                   한세실업                케이카               세방전지  \
2021  1,620,351,194,651  1,902,394,224,458  1,243,923,315,980

               화승엔터프라이즈               보령
2021  1,138,575,157,941  594,412,561,628

[1 rows x 143 columns]

In [105]:
df2222 = pd.concat([df, df1, df2, df3, df4, df5], axis=0)
df2222.dropna(axis=1, inplace=True)
df2222.head()

,삼성전자,SK하이닉스,삼성SDI,LG화학,NAVER,POSCO홀딩스,현대모비스,포스코케미칼,LG전자,SK이노베이션,...,KG스틸,녹십자홀딩스,대상,현대그린푸드,한섬,현대홈쇼핑,한세실업,세방전지,화승엔터프라이즈,보령
2016,"133,947,204,000,000","16,733,111,000,000","4,422,860,766,602","17,264,845,000,000","2,496,498,317,219","24,324,933,259,995","19,860,589,000,000","1,076,455,299,180","28,743,246,000,000","1,199,714,934,000",...,"1,542,880,719,243","98,335,181,791","1,852,714,894,145","1,554,226,963,000","710,321,856,289","961,339,683,153","1,421,975,960,308","958,982,088,874","35,967,805,991","409,140,006,900"
2017,"161,915,007,000,000","29,718,939,000,000","5,421,388,951,623","20,880,236,000,000","2,930,661,324,862","28,553,814,576,380","19,417,685,000,000","1,163,917,965,558","31,966,513,000,000","3,103,342,788,000",...,"1,733,421,115,227","115,366,470,969","2,190,129,354,256","1,477,451,922,000","765,914,995,234","1,021,841,020,147","1,354,626,971,623","1,108,228,132,369","768,224,189,587","422,721,051,680"
2018,"170,381,870,000,000","40,324,651,000,000","8,186,909,424,218","23,315,318,000,000","3,459,014,042,545","30,659,425,433,515","20,517,169,000,000","1,340,983,671,872","29,982,010,000,000","3,679,762,542,000",...,"1,750,903,867,403","140,083,965,948","2,235,924,262,966","1,514,615,128,000","766,644,344,598","973,453,833,250","1,316,638,246,722","1,165,728,777,090","879,226,467,059","460,401,670,473"
2019,"154,772,859,000,000","25,320,755,000,000","8,250,811,204,936","22,312,561,000,000","3,900,013,295,633","30,373,510,738,515","22,624,741,000,000","1,434,507,298,627","28,654,467,000,000","3,006,128,697,000",...,"1,688,470,941,497","63,553,294,669","2,457,055,173,045","1,542,730,568,000","994,560,575,546","1,030,416,792,521","1,533,976,204,952","1,129,805,364,875","1,201,591,250,778","524,268,670,098"
2020,"166,311,191,000,000","30,524,987,000,000","9,101,397,946,638","20,830,009,000,000","4,126,629,312,584","26,509,920,446,184","22,954,483,000,000","1,524,145,792,626","28,435,323,000,000","3,808,247,747,000",...,"2,098,691,005,565","78,784,538,818","2,604,922,341,877","1,512,503,414,000","1,194,779,636,319","1,084,990,445,012","1,657,328,003,744","1,077,016,196,453","1,115,756,451,023","541,445,421,587"